# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod ‘Alamofire’
   pod ‘SwiftyJSON’
  # Pods for SampleTableView

  target 'SampleTableViewTests' do
    inherit! :search_paths
    # Pods for testing
	pod ‘Alamofire’
	   pod ‘SwiftyJSON’
  end

  target 'SampleTableViewUITests' do
    # Pods for testing
	pod ‘Alamofire’
	   pod ‘SwiftyJSON’
  end

end
